apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v2
  labels:
    app: myapp
    version: v2
spec:
  replicas: 2  # 2 pods para V2
  selector:
    matchLabels:
      app: myapp
      version: v2
  template:
    metadata:
      labels:
        app: myapp
        version: v2
    spec:
      containers:
      - name: nginx
        image: myapp:v2
        imagePullPolicy: Never  # Usa la imagen local de Minikube
        ports:
        - containerPort: 80